#!/bin/bash

### BEGIN INIT INFO
# Provides:          tomcat
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: starts the tomcat
# Description:       starts tomcat
### END INIT INFO

#
# tomcat
#
# chkconfig: - 98 02
# description: Start up the Tomcat servlet engine.

RETVAL=0
CATALINA_HOME="/opt/tomcat"
USER=tomcat

JAVAOPTS=""

tomcat_pid() {
  echo `ps aux | grep org.apache.catalina.startup.Bootstrap | grep -v grep | awk '{ print $2 }'`
  }

start(){
    pid=$(tomcat_pid)
    if [ -n "$pid" ]
        then
        echo "Tomcat is already running (pid: $pid)"
        else
        [ -f $CATALINA_HOME/bin/startup.sh ] && {
            echo $"Starting Tomcat"
            if [ $UID = 0 ]; then
                su - $USER -c "JAVA_OPTS=\"$JAVAOPTS\" $CATALINA_HOME/bin/startup.sh"
            else
               JAVA_OPTS=\"$JAVAOPTS\" $CATALINA_HOME/bin/startup.sh
            fi
        }
    fi
}

stop(){
        [ -f $CATALINA_HOME/bin/shutdown.sh ] && {
            echo $"Stopping Tomcat"
            if [ $UID = 0 ]; then
                su - $USER -c "$CATALINA_HOME/bin/shutdown.sh"
                sleep 5
                pid=$(tomcat_pid)
                if [ -n "$pid" ]
                    then
                        kill -9 $pid
                        echo "Tomcat has been killed"
                fi
            else
                $CATALINA_HOME/bin/shutdown.sh
                sleep 5
                pid=$(tomcat_pid)
                if [ -n "$pid" ]
                    then
                        kill -9 $pid
                        echo "Tomcat has been killed"
                fi
            fi
        }
}


case "$1" in
    start)
        start
        ;;
    stop)
        stop
        ;;
    restart)
        stop
        sleep 3
        start
        ;;
    status)
        pid=$(tomcat_pid)
        if [ -n "$pid" ]
            then
                echo "Tomcat is running with pid: $pid"
            else
                echo "Tomcat is not running"
                RETVAL=1
        fi
        ;;
     *)
        echo $"Usage: $0 {start|stop|restart|status}"
        RETVAL=1
        ;;
esac

exit $RETVAL

